#!/usr/bin/env node
/**
 * Seed script for Milwaukee 2026 Budget data into Convex.
 *
 * Usage:
 *   npx convex run seed:seedAll
 *
 * Or run this script directly after setting CONVEX_URL:
 *   node seedFromJson.mjs
 *
 * This reads the JSON files generated by parse_budget_v2.py
 * and inserts them into the Convex database.
 */

import { ConvexHttpClient } from "convex/browser";
import { api } from "./_generated/api.js";
import fs from "fs";

const client = new ConvexHttpClient(process.env.CONVEX_URL);

// Helper: snake_case → camelCase
function toCamelCase(obj) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const camelKey = key.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
    result[camelKey] = value ?? undefined;
  }
  return result;
}

async function seedTable(tableName, jsonFile, transform) {
  const raw = JSON.parse(fs.readFileSync(jsonFile, "utf-8"));
  const rows = Array.isArray(raw) ? raw : [raw];
  console.log(`Seeding ${tableName}: ${rows.length} rows from ${jsonFile}`);

  // Batch in groups of 50 to avoid timeouts
  const BATCH_SIZE = 50;
  let total = 0;
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE).map((row) => {
      const camel = toCamelCase(row);
      return transform ? transform(camel) : camel;
    });
    await client.mutation(api.seed.batchInsert, {
      table: tableName,
      rows: batch,
    });
    total += batch.length;
  }
  console.log(`  ✓ Inserted ${total} rows into ${tableName}`);
}

async function main() {
  console.log("🏙️  Milwaukee 2026 Budget → Convex Seeder\n");

  // 1. City overview
  await client.mutation(api.seed.seedCityOverview);
  console.log("✓ cityOverview seeded");

  // 2. Budget sections (hardcoded in seed.ts)
  await client.mutation(api.seed.seedBudgetSections);
  console.log("✓ budgetSections seeded (12 sections)");

  // 3. Appropriation details
  await seedTable("appropriationDetails", "appropriation_details.json");

  // 4. Department budgets
  await seedTable("departmentBudgets", "department_budgets.json");

  // 5. Department meta
  await seedTable("departmentMeta", "department_meta.json");

  // 6. Department services
  await seedTable("departmentServices", "department_services.json");

  // 7. Performance measures
  await seedTable("performanceMeasures", "performance_measures.json");

  // 8. Positions
  await seedTable("positions", "positions.json");

  // 9. Historical comparison
  await seedTable("historicalComparison", "historical_comparison.json");

  // 10. Narratives
  await seedTable("departmentNarratives", "department_narratives.json");

  console.log("\n✅ All tables seeded successfully!");
}

main().catch(console.error);
